bundled_packages_dir: packages
data_dir: data
description: MPT-7B is an LLM in the MosaicML Foundation Series
environment_variables: {}
examples_filename: examples.yaml
input_type: Any
live_reload: false
model_class_filename: model.py
model_class_name: Model
model_framework: custom
model_metadata:
  tags:
  - text-generation
model_module_dir: model
model_name: MPT-7B
model_type: custom
python_version: py39
requirements:
  - transformers
  - torch
  - einops 
  - sentencepiece
resources:
  cpu: "3"
  memory: 50Gi
  use_gpu: true
  accelerator: T4
secrets: {}
spec_version: '2.0'
system_packages: []
